### ISSUE TITLE
The following module(s) are unknown: "bowtie"

### ISSUE THREAD

**Issue by ramostapiai** [mhalushka/miRge3.0#18]
Thanks for developing the software, I think it will be of great help for the research.
I have a problem, when installing miRge3.0 through conda I get the following error and I don't know how to solve it: Bowtie is as a command in the environment created for miRge3.0.

Lmod has detected the following error: The following module (s) are unknown:
"bowtie"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
   $ module --ignore-cache load "bowtie"

Also make sure that all modulefiles written in TCL start with the string
#% Module

Lmod has detected the following error: The following module (s) are unknown:
"bowtie"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
   $ module --ignore-cache load "bowtie"

Also make sure that all modulefiles written in TCL start with the string
#% Module

Greetings

**Comment by arunhpatil** [comment]
Hi @ramostapiai, 

Thank you. Installation with Conda is the ideal way to go. I believe that you are installing miRge3.0 on the base environment on your cluster (which is interfering with other modules). Can you try creating an environment and install miRge3.0 as shown below: 

```
conda create --name myenv
conda activate myenv 
conda install -c bioconda mirge3
```
To come out of the virtual enviroment `myenv`, type the following command 
```
conda deactivate 
```

Please let me know if this solution works. If the bowtie is already installed on your server (you can check by `module spider bowtie`), installation of bowtie with conda on the base environment might throw such an error. It is ideal to use virtual environments as shown above. 

Thank you,
Arun.

**Comment by ramostapiai** [comment]
Hi @arunhpatil,

Thanks for the reply. In fact it is in an exclusive environment of mirge3, anyway I have done it again and the problem persists.

bowtie error !: bowtie, command not found
Use argument -pbwt <name of the directory>

By typing bowtie -h inside the environment bowtie is there:
bowtie -h
usage: bowtie [-h] [-b | -i] [--verbose] [--debug] [--large-index]
               [--index INDEX]

optional arguments:
   -h, --help show this help message and exit
   -b, --build
   -i, --inspect
   --verbose
   --debug
   --large-index
   --index INDEX

How other option i have?

Thanks again
Ignacio

**Comment by ramostapiai** [comment]
Thanks for the help.
I tell you, which bowtie works, but locate bowtie doesn't. I have given the path from bowtie to mirge3 and it has not worked again:

bowtie error !: bowtie, command not found
Use argument -pbwt <name of the directory>

Check if conda is not in the path and add it to the bash_profile of the cluster user,

**Comment by arunhpatil** [comment]
Hi, can you share the command you are using (with and without -pbwt)? That will help me to rule out what could be wrong. (You may keep synonym for file name -s file_name.fastq.gz) 

Thank you,
Arun.

**Comment by ramostapiai** [comment]
Yes of course I can, I have previously defined the input and output directories and made an array for my 694 samples.
Maybe I am performing many actions perhaps, but I could not find the simplest base command of mirge3.

i=$(sed -n "$SLURM_ARRAY_TASK_ID"p /home/sample_list.txt)

source activate /GWSPH/home/ecastron/miniconda3/envs/mirge3

#directories
fastq="/home/raw_data/sequences"
output="home/output_mirge3"

miRge3.0 \
-s $fastq/${i}_R1_trimmed.fastq.gz \
-lib miRge3_Lib \
-on human \
-db /home/miRge3_Lib \
-o $output \
-gff \
-bam \
-nmir \
-trf \
-ai \
-cpu 16 \
-pbwt /home/ecastron/miniconda3/envs/mirge3/bin/bowtie

**Comment by arunhpatil** [comment]
Ok. small correction, please provide this `-pbwt /home/miniconda3/envs/mirge3/bin` instead of `-pbwt /home/miniconda3/envs/mirge3/bin/bowtie`.  Also, -db should be either `miRBase `or `miRGeneDB`. 

This should fix the problem. However, I recommend you to test 2 samples at first as shown below:
example: miRge3.0 -s infile1.fastq.gz,infile2.fastq.gz -lib miRge3_Lib -on human -db miRGeneDB -o output_dir -gff -nmir -trf -ai -cpu 16 -pbwt  /home/miniconda3/envs/mirge3/bin

Please let me know if this works. 

Thanks, 
Arun.

**Comment by ramostapiai** [comment]
Ok, I have made the corrections but it is still the same error: bowtie error !: bowtie, command not found. I have tried with only one sample but the problem persists.

**Comment by arunhpatil** [comment]
Hi @ramostapiai, 

I want to try one last thing. Can you check the version of the bowtie using the complete path as shown below?  If this doesn't work out, is it possible to have a zoom meeting so I can quickly check the issue? 

`/home/miniconda3/envs/mirge3/bin/bowtie --version`

Thank you,
Arun.

**Comment by ramostapiai** [comment]
Oops !, I think my conda is not working well or there is something else.
With regard to zoom there is no problem another day, I apologize if my English is not the best in the world. I try to improve it

~/miniconda3/envs/mirge3/bin/bowtie --version
~/home/miniconda3/envs/mirge3/bin/bowtie-align-s: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory

**Comment by arunhpatil** [comment]
Hi @ramostapiai, 

Great, now I know the error. You need to call this library (tbb) prior to calling bowtie. If you are using a cluster with support to slurm/module you can look for tbb by `module spider tbb`. You could install/load  `tbb/4.1` which I think is the latest version. If you can load this library, this issue will be resolved.  See if this works, I will tell you how to make this a permanent set up on the cluster. 

Thank you,
Arun.

**Comment by arunhpatil** [comment]
@ramostapiai, Awesome. I am glad it worked.
